name: flutter_attendance_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true